---
- name: Deploy
  hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
    - name: create shared files
      file:
        path: "{{ deploy_path }}/{{ item.site }}/shared/{{ item.site }}/public/{{ item.folder}}"
        state: directory
        mode: 0755
      with_items:
        - {site: backend, folder: css}
        - {site: backend, folder: js}
        - {site: backend, folder: uploads}

        - {site: frontend, folder: css}
        - {site: frontend, folder: js}
        - {site: frontend, folder: uploads}

    - name: deploy
      become: yes
      include_role:
        name: carlosbuenosvinos.ansistrano-deploy

      vars:
        ansistrano_deploy_from: "{{ playbook_dir }}/../{{ item }}"
        ansistrano_deploy_to: "{{ deploy_path }}/{{ item }}"
        ansistrano_ensure_shared_paths_exist: yes
        ansistrano_ensure_basedirs_shared_files_exist: yes
        ansistrano_keep_releases: 5
        ansistrano_allow_anonymous_stats: false
        ansistrano_shared_paths:
          - "{{ item }}/public/css"
          - "{{ item }}/public/js"
          - "{{ item }}/public/uploads"

        ansistrano_shared_files: []

        # There seems to be an issue with rsync in vagrant
        ansistrano_deploy_via: rsync

      apply:
        - become

      with_items:
        - backend
        - frontend
