- name: Provision
  hosts: all
  gather_facts: yes

  become_method: sudo
  become_user: root
  become: yes

  vars_files:
    - vars/main.yml
    - vars/common.yml
    - "{{ playbook_dir }}/host_vars/{{ ansible_hostname }}.yml"

    - vars/secret.yml

  roles:
    - role: geerlingguy.firewall

    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'

    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - role: geerlingguy.mysql

    - role: ../roles/openresty

    - role: geerlingguy.php-versions
    - role: geerlingguy.php
