---
- src: geerlingguy.firewall
- src: geerlingguy.repo-epel
- src: geerlingguy.repo-remi
- src: geerlingguy.mysql
- src: geerlingguy.varnish
- src: geerlingguy.certbot
- src: geerlingguy.pip
- src: geerlingguy.php
- src: geerlingguy.php-versions